### ISSUE TITLE
typo in section 12_detr

### ISSUE THREAD

**Issue by amirhosseinmhd** [adensur/blog#1]
in section 12 there is a typo about dot product, here is the corrected version: 

... Dot product geometric interpretation is "orthogonality": the dot product is **minimal** if the vectors are orthogonal to each other...

**Comment by adensur** [comment]
[fix](https://github.com/adensur/blog/commit/ca38e0dc110b409792fb7b92fcb37bb9e32b3298)
Thanks for the comment!
